name: CzechCore
version: 1.0
main: me.jules.czechcore.CzechCore
api-version: 1.21
commands:
  home:
    description: Otevře menu domovů nebo tě teleportuje.
    usage: /home [číslo]
  sethome:
    description: Nastaví domov.
    usage: /sethome [číslo]
  tpa:
    description: Žádost o teleport k hráči.
    usage: /tpa <hráč>
  tpahere:
    description: Žádost, aby se hráč teleportoval k tobě.
    usage: /tpahere <hráč>
  tpacancel:
    description: Zruší tvou odeslanou žádost o teleport.
    usage: /tpacancel
  tpaoff:
    description: Přepne přijímání žádostí o teleport.
    usage: /tpaoff
  tpaccept:
    description: Přijme žádost o teleport.
    usage: /tpaccept
    aliases: [tpaaccept]
  tpadeny:
    description: Odmítne žádost o teleport.
    usage: /tpadeny
    aliases: [tpdeny, tpa-deny]
  spawn:
    description: Teleport na spawn.
    usage: /spawn
  setspawn:
    description: Nastaví lokaci spawnu.
    usage: /setspawn
  gmc:
    description: Změní herní mód na kreativní.
    usage: /gmc
  gms:
    description: Změní herní mód na survival.
    usage: /gms
  gmsp:
    description: Změní herní mód na spectator.
    usage: /gmsp
  gma:
    description: Změní herní mód na adventure.
    usage: /gma
  rtp:
    description: Náhodný teleport.
    usage: /rtp
  flyspeed:
    description: Nastaví tvou rychlost létání.
    usage: /flyspeed [1-10]
  playtime:
    description: Ukáže odehraný čas.
    usage: /playtime [hráč]
  coinflip:
    description: Hazardní hra coinflip.
    usage: /coinflip [částka]
    aliases: [cf]
  invsee:
    description: Zobrazí inventář jiného hráče.
    usage: /invsee <hráč>
permissions:
  czechcore.home:
    description: Přístup k příkazům domovů.
    default: true
  czechcore.tpa:
    description: Přístup k TPA příkazům.
    default: true
  czechcore.spawn:
    description: Přístup k příkazům spawnu.
    default: true
  czechcore.admin:
    description: Přístup k administrátorským příkazům.
    default: op
  czechcore.gmc:
    description: Přístup k /gmc.
    default: op
  czechcore.gms:
    description: Přístup k /gms.
    default: op
  czechcore.gmsp:
    description: Přístup k /gmsp.
    default: op
  czechcore.gma:
    description: Přístup k /gma.
    default: op
  czechcore.rtp:
    description: Přístup k /rtp.
    default: true
  czechcore.flyspeed:
    description: Přístup k /flyspeed.
    default: op
  czechcore.playtime:
    description: Přístup k /playtime.
    default: true
  czechcore.coinflip:
    description: Přístup k /coinflip.
    default: true
  czechcore.invsee:
    description: Přístup k /invsee.
    default: op
  czechcore.home.0:
    default: true
  czechcore.home.1:
    default: true
  czechcore.home.2:
    default: false
  czechcore.home.3:
    default: false
  czechcore.home.4:
    default: false
  czechcore.home.5:
    default: false
  czechcore.home.6:
    default: false
  czechcore.home.7:
    default: op
