name: MagioCore
version: 1.0
main: me.jules.magiocore.MagioCore
api-version: 1.21
commands:
  home:
    description: Open the home GUI or teleport to a home.
    usage: /home [number]
  sethome:
    description: Set a home.
    usage: /sethome [number]
  tpa:
    description: Request to teleport to a player.
    usage: /tpa <player>
  tpahere:
    description: Request a player to teleport to you.
    usage: /tpahere <player>
  tpacancel:
    description: Cancel your sent TPA request.
    usage: /tpacancel
  tpaoff:
    description: Toggle TPA requests.
    usage: /tpaoff
  tpaccept:
    description: Accept a TPA request.
    usage: /tpaccept
    aliases: [tpaaccept]
  tpadeny:
    description: Deny a TPA request.
    usage: /tpadeny
    aliases: [tpdeny, tpa-deny]
  spawn:
    description: Teleport to spawn.
    usage: /spawn
  setspawn:
    description: Set the spawn location.
    usage: /setspawn
  gmc:
    description: Change gamemode to creative.
    usage: /gmc
  gms:
    description: Change gamemode to survival.
    usage: /gms
  gmsp:
    description: Change gamemode to spectator.
    usage: /gmsp
  gma:
    description: Change gamemode to adventure.
    usage: /gma
  rtp:
    description: Random teleport.
    usage: /rtp
permissions:
  magiocore.home:
    description: Access to home commands.
    default: true
  magiocore.tpa:
    description: Access to TPA commands.
    default: true
  magiocore.spawn:
    description: Access to spawn commands.
    default: true
  magiocore.admin:
    description: Access to admin commands like /setspawn.
    default: op
  magiocore.gmc:
    description: Access to /gmc.
    default: op
  magiocore.gms:
    description: Access to /gms.
    default: op
  magiocore.gmsp:
    description: Access to /gmsp.
    default: op
  magiocore.gma:
    description: Access to /gma.
    default: op
  magiocore.rtp:
    description: Access to /rtp.
    default: true
