# MagioCore Config

# Join Message Settings
join-message:
  show-head: true

  # Global message shown when a player joins for the first time
  first-join:
    format: "&#00fbff%player% §7se poprvé připojil! Vítej na &#00fbffCZSK SMP!"
    side-messages:
      - ""
      - "&#00fbffVÍTEJ"
      - "§7Hráč &#00fbff%player%"
      - "§7se poprvé"
      - "§7připojil na"
      - "&#00fbffCZSK SMP!"
      - ""
      - "§7Užij si to!"

  # Private message shown to the player when they login
  private-welcome:
    format: "§7Vítej zpět, &#00fbff%player%§7! Doufáme, že si tu užiješ čas."
    side-messages:
      - ""
      - "&#00fbffVÍTEJ ZPĚT"
      - "§7Ahoj &#00fbff%player%§7!"
      - "§7Doufáme, že si"
      - "§7u nás na serveru"
      - "§7užiješ spoustu"
      - "§7zábavy!"
      - "§7Šťastné hraní!"

# AFK Zone Settings
afk-zone:
  region-name: "afk"
  reward-command: "eco give %player% 10" # Command to run every minute

# Anti Spam Settings
anti-spam:
  delay: 2 # Delay in seconds between messages

# RTP GUI Settings
rtp:
  gui:
    title: "ᴡᴏʀʟᴅ sᴇʟᴇᴄᴛɪᴏɴ"
    rows: 3
    background: "AIR"
    worlds:
      overworld:
        material: "PLAYER_HEAD"
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2U1MTA4YzljMjljNzRjM2FmMzk2MWI4ZTAyY2NkZjFkNTE3ZmZiOTYwMzUwNTVmNTIzZTc1MzM5Nzk1ZDEzMyJ9fX0="
        slot: 11
        name: "ᴏᴠᴇʀᴡᴏʀʟᴅ"
        lore:
          - "§7Klikni zde pro náhodnou teleportaci"
          - "§7někam do světa overworld."
          - ""
          - "&#00ff44> KLIKNI PRO TELEPORTACI"
      nether:
        material: "NETHERRACK"
        slot: 13
        name: "ɴᴇᴛʜᴇʀ"
        lore:
          - "§7Klikni zde pro náhodnou teleportaci"
          - "§7někam do pekla."
          - ""
          - "&#ff4444> KLIKNI PRO TELEPORTACI"
      end:
        material: "END_STONE"
        slot: 15
        name: "ᴇɴᴅ"
        lore:
          - "§7Klikni zde pro náhodnou teleportaci"
          - "§7někam do endu."
          - ""
          - "&#ff00ff> KLIKNI PRO TELEPORTACI"
  settings:
    radius: 5000
    max-attempts: 10

# Spawn Location
spawn: null
